---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dao-service
  labels:
    app: dao-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dao-service
    spec:
      containers:
      - name: dao-service
        image: dao-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: dao-service
  labels:
    app: dao-service
spec:
  ports:
  - port: 9080
    name: http 
  selector:
    app: dao-service
