---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mvc-service-brown
  labels:
    app: mvc-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mvc-service
        version: brown
    spec:
      containers:
      - name: mvc-service
        image: mvc-service:brown
        imagePullPolicy: Never
        ports:
        - containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: mvc-service
  labels:
    app: mvc-service
spec:
  type: NodePort
  ports:
  # the port that this service should serve on
  - port: 3333
    targetPort: 3333
    nodePort: 31190
  selector:
    app: mvc-service