---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mvc-service-blue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mvc-service
        version: blue
    spec:
      containers:
      - name: mvc-service
        image: mvc-service:blue
        imagePullPolicy: Never
        ports:
        - containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: mvc-service
  labels:
    app: mvc-service
spec:
  type: NodePort
  ports:
  - port: 3333
  selector:
    app: mvc-service